name: Refresh README workflow

on:
  schedule:
    - cron: '30 4 * * *'
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  refresh_readme:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Default metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Syrent
          template: classic
          base: header, activity, community, repositories, metadata
          config_octicon: yes
          config_timezone: Iran/Tehran
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 10
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 5
          plugin_lines_sections: base
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: icons
          plugin_topics_sort: starred
          plugin_traffic: yes
          committer_message: ':zap: [ci skip] Update README'
