name: Refresh README workflow

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  refresh_readme:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Default metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: TheWylot
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Dubai
          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_sections: repositories
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          plugin_people: yes
          plugin_people_limit: 10
          plugin_people_size: 28
          plugin_people_types: followers, following
          plugin_achievements: yes
          plugin_achievements_only: >-
            polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
            scripter, packager, explorer, infographile, manager
          plugin_achievements_display: compact
          plugin_achievements_threshold: X
          plugin_stars: yes
          plugin_stars_limit: 1
          committer_message: ':zap: [ci skip] Update README File'
